### ISSUE TITLE
strange make_pers behavior

### ISSUE THREAD

**Issue by nborggren** [geomdata/gda-public#14]
If make_pers() gets called twice, all but one point in the persistence diagram is overwritten.  Use np.copy(values) rather than values in unionfind?

![image](https://user-images.githubusercontent.com/4954946/35169632-3485a174-fd2b-11e7-96a0-da7c1bd07f6e.png)

**Comment by curieux** [comment]
I think this is probably due to the way that the root-finding indexing and pos/neg marking happens.  This sort of issue is why the `reset()` function exists in `mutlidim.__init__`.  There should probably be a version of that in `timeseries`,too.

I don't think we want to do copy for performance reasons (taking a O(log(n)) algorithm to a O(n) algorithm!) but we can maybe do a check and throw a warning.

**Comment by curieux** [comment]
this may be more clear in b3ea510f
